kind: pipeline
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.4.1
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - dapper ci
  - name: stage-binaries
    image: rancher/dapper:v0.4.1
    commands:
      - cp -r ./bin/* ./package/
      - ls ./bin
    when:
      event:
        - tag
        - push
  - name: cache-amd64-bin
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - bin
        - package
    volumes:
      - name: amd64-bin
        path: /cache
    when:
      event:
        - tag
        - push
  # - name: stage-binaries
  #   image: rancher/dapper:v0.4.1
  #   commands:
  #     - cp -r ./bin/* ./package/
  #     - ls ./bin
  #   when:
  #     event:
  #       - tag
  #       - push
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: amd64-bin
    host:
        path: /tmp/rancher/amd64bin
# ---
# kind: pipeline
# name: build-arm64

# platform:
#   os: linux
#   arch: arm64

# steps:

#   - name: build
#     image: rancher/dapper:v0.4.1
#     volumes:
#       - name: docker
#         path: /var/run/docker.sock
#       - name: arm64-binaries
#         path: /tmp/arm64-binaries
#     commands:
#       - dapper ci
#   - name: stage-binaries
#     image: rancher/dapper:v0.4.1
#     commands:
#       - cp -r ./bin/* ./package/
#       - cp -r ./bin/* /tmp/arm64-binaries
#       - sed -i -e '$a\' -e 'ENV ETCD_UNSUPPORTED_ARCH=arm64' package/Dockerfile
#     when:
#       event:
#         - tag
#         - push
# volumes:
#   - name: docker
#     host:
#       path: /var/run/docker.sock
#   - name: arm64-binaries
#     temp: {}
---
kind: pipeline
name: publish-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: restore-amd64-bin
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - bin
        - package
    volumes:
      - name: amd64-bin
        path: /cache
  - name: publish-master-amd64
    image: plugins/docker
    commands:
      - ls ./package/
      - ls ./bin/
    environment:
      PLUGIN_CUSTOM_DNS: 1.1.1.1
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: package/Dockerfile
      context: package/
      build_args:
        - ARCH=amd64
        - VERSION=master
      repo: jianghang8421/rancher
      tag: "test-amd64"
    when:
      branch: 
        - multiarch-support
      event:
        - push
  - name: publish-master-agent-amd64
    image: plugins/docker
    commands:
      - cp -r /tmp/amd64-binaries/* ./package/
    environment:
      PLUGIN_CUSTOM_DNS: 1.1.1.1
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: package/Dockerfile.agent
      context: package/
      build_args:
        - ARCH=amd64
        - VERSION=v2.2-multiarch
      repo: jianghang8421/rancher-agent
      tag: "test-amd64"
    when:
      branch: 
        - multiarch-support
      event:
        - push
  - name: publish-amd64
    image: plugins/docker
    environment:
      PLUGIN_CUSTOM_DNS: 1.1.1.1
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: package/Dockerfile
      context: package/
      build_args:
        - ARCH=amd64
        - VERSION=${DRONE_TAG}
      repo: jianghang8421/rancher
      tag: "${DRONE_TAG}-amd64"
    when:
      event:
        - tag
  - name: publish-agent-amd64
    image: plugins/docker
    environment:
      PLUGIN_CUSTOM_DNS: 1.1.1.1
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: package/Dockerfile.agent
      context: package/
      build_args:
        - ARCH=amd64
        - VERSION=master
      repo: jianghang8421/rancher-agent
      tag: "${DRONE_TAG}-amd64"
    when:
      event:
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
  - name: amd64-bin
    host:
        path: /tmp/rancher/amd64bin
depends_on:
- build-amd64
# - build-arm64
# ---
# kind: pipeline
# name: publish-arm64

# platform:
#   os: linux
#   arch: arm64

# steps:
#   - name: publish-master-arm64
#     image: plugins/docker
#     commands:
#       - cp -r /tmp/arm64-binaries/* ./package/
#     environment:
#       PLUGIN_CUSTOM_DNS: 1.1.1.1
#     settings:
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       dockerfile: package/Dockerfile
#       context: package/
#       build_args:
#         - ARCH=arm64
#         - VERSION=v2.2-multiarch
#       repo: jianghang8421/rancher
#       tag: "master-arm64"
#     when:
#       branch: 
#         - multiarch-support
#       event:
#         - push
#   - name: publish-master-agent-arm64
#     image: plugins/docker
#     commands:
#       - cp -r /tmp/arm64-binaries/* ./package/
#     environment:
#       PLUGIN_CUSTOM_DNS: 1.1.1.1
#     settings:
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       dockerfile: package/Dockerfile.agent
#       context: package/
#       build_args:
#         - ARCH=arm64
#         - VERSION=v2.2-multiarch
#       repo: jianghang8421/rancher-agent
#       tag: "master-arm64"
#     when:
#       branch: 
#         - multiarch-support
#       event:
#         - push
#   - name: publish-arm64
#     image: plugins/docker
#     environment:
#       PLUGIN_CUSTOM_DNS: 1.1.1.1
#     settings:
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       dockerfile: package/Dockerfile
#       context: package/
#       build_args:
#         - ARCH=arm64
#         - VERSION=${DRONE_TAG}
#       repo: jianghang8421/rancher
#       tag: "${DRONE_TAG}-arm64"
#     when:
#       event:
#         - tag
#   - name: publish-agent-arm64
#     image: plugins/docker
#     environment:
#       PLUGIN_CUSTOM_DNS: 1.1.1.1
#     settings:
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       dockerfile: package/Dockerfile.agent
#       context: package/
#       build_args:
#         - ARCH=arm64
#         - VERSION=master
#       repo: jianghang8421/rancher-agent
#       tag: "${DRONE_TAG}-arm64"
#     when:
#       event:
#         - tag
# volumes:
#   - name: docker
#     host:
#       path: /var/run/docker.sock
# depends_on:
# - build-amd64
# - build-arm64
# ---
# kind: pipeline
# name: publish-manifest

# steps:
#   - name: push-master-manifest
#     image: plugins/manifest:1.0.2
#     settings:
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       target: "jianghang8421/rancher:master"
#       template: "jianghang8421/rancher:master-ARCH"
#       platforms:
#         - linux/amd64
#         - linux/arm64
#     when:
#       branch:
#         - multiarch-support
#       event:
#         - push
#   - name: push-master-agent-manifest
#     image: plugins/manifest:1.0.2
#     settings:
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       target: "jianghang8421/rancher-agent:master"
#       template: "jianghang8421/rancher-agent:master-ARCH"
#       platforms:
#         - linux/amd64
#         - linux/arm64
#     when:
#       branch:
#         - multiarch-support
#       event:
#         - push
#   - name: push-manifest
#     image: plugins/manifest:1.0.2
#     settings:
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       target: "jianghang8421/rancher:${DRONE_TAG}"
#       template: "jianghang8421/rancher:${DRONE_TAG}-ARCH"
#       platforms:
#         - linux/amd64
#         - linux/arm64
#     when:
#       event:
#         - tag
#   - name: push-agent-manifest
#     image: plugins/manifest:1.0.2
#     settings:
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       target: "jianghang8421/rancher-agent:${DRONE_TAG}"
#       template: "jianghang8421/rancher-agent:${DRONE_TAG}-ARCH"
#       platforms:
#         - linux/amd64
#         - linux/arm64
#     when:
#       event:
#         - tag
# depends_on:
# - publish-amd64
# - publish-arm64
