FROM ubuntu:18.04
ARG ARCH=amd64
ENV DOCKER_URL_amd64=https://get.docker.com/builds/Linux/x86_64/docker-1.10.3 \
    DOCKER_URL_arm64=https://github.com/rancher/docker/releases/download/v1.10.3-ros1/docker-1.10.3_arm64 \
    DOCKER_URL=DOCKER_URL_${ARCH}

RUN rm -f /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates jq iproute2 vim-tiny less bash-completion unzip && \
    curl -sLf ${!DOCKER_URL} > /usr/bin/docker && \
    chmod +x /usr/bin/docker && \
    curl -sLf https://storage.googleapis.com/kubernetes-release/release/v1.10.5/bin/linux/${ARCH}/kubectl > /usr/bin/kubectl && \
    chmod +x /usr/bin/kubectl && \
    DEBIAN_FRONTEND=noninteractive apt-get autoremove -y && \
    DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ENV LOGLEVEL_VERSION v0.1

ENV LOGLEVEL_URL_amd64=https://github.com/rancher/loglevel/releases/download/${LOGLEVEL_VERSION}/loglevel-${ARCH}-${LOGLEVEL_VERSION}.tar.gz \
    LOGLEVEL_URL_arm64=https://github.com/jianghang8421/loglevel/releases/download/v0.1-arm64/loglevel-${ARCH}-${LOGLEVEL_VERSION}.tar.gz \
    LOGLEVEL_URL=LOGLEVEL_URL_${ARCH}

ENV SHARE_MNT_URL_amd64=https://github.com/rancher/share-mnt/releases/download/v1.0.3/share-mnt.tar.gz \
    SHARE_MNT_URL_arm64=https://github.com/jianghang8421/share-mnt/releases/download/v1.0.3-multiarch/share-mnt-arm64.tar.gz \
    SHARE_MNT_URL=SHARE_MNT_URL_${ARCH}

RUN curl -sLf ${!LOGLEVEL_URL} | tar xvzf - -C /usr/bin
RUN curl -sL ${!SHARE_MNT_URL} | tar xvzf - -C /usr/bin
ENV KUBEPROMPT_VERSION v1.0.5
ENV KUBEPROMPT_URL_amd64=https://github.com/c-bata/kube-prompt/releases/download/${KUBEPROMPT_VERSION}/kube-prompt_${KUBEPROMPT_VERSION}_linux_amd64.zip \
    KUBEPROMPT_URL_arm64=https://github.com/jianghang8421/kube-prompt/releases/download/v1.0.5-multiarch/kube-prompt_v1.0.5-multiarch_linux_arm64.zip \
    KUBEPROMPT_URL=KUBEPROMPT_URL_${ARCH}

RUN curl -sL ${!KUBEPROMPT_URL} > /usr/bin/kube-prompt.zip && unzip /usr/bin/kube-prompt.zip -d /usr/bin
ARG VERSION=dev
LABEL io.cattle.agent true
ENV DOCKER_API_VERSION 1.24
ENV AGENT_IMAGE rancher/rancher-agent:${VERSION}
ENV SSL_CERT_DIR /etc/kubernetes/ssl/certs
COPY agent run.sh kubectl-shell.sh shell-setup.sh share-root.sh /usr/bin/
ENTRYPOINT ["run.sh"]
