name: Unit Tests
on: [workflow_dispatch, workflow_call]
jobs:
  unit-test:
    env:
      GOLANG_VERSION: '1.22'
    runs-on: test-runner-1
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: Run unit tests
        run: go test -cover -tags=test ./pkg/...

